'use client';
import {useMemo,useState} from 'react';
type Locale='ar'|'en';
const services=[['website','🌐','موقع إلكتروني','Website'],['system','⚙️','نظام / برنامج','System / Software'],['store','🛒','متجر إلكتروني','E-Commerce'],['social','🎨','تصميم سوشيال ميديا','Social Media'],['full','🚀','مشروع متكامل','Full Digital Project'],['unsure','❓','لست متأكدًا','Not Sure']];
export default function ProjectBuilder({locale}:{locale:Locale}){const ar=locale==='ar';const [step,setStep]=useState(1);const [service,setService]=useState('');const [details,setDetails]=useState<Record<string,string>>({});const total=4;const types=useMemo(()=>service==='system'?['ERP','CRM','POS','Inventory','HR','Booking','Accounting','Customer Portal','Custom System']:service==='social'?['One design','Campaign','Monthly package','Product launch','Stories','Ads','Full social identity']:['Company Website','Landing Page','Online Store','Booking Website','Marketplace','Personal / Portfolio','Other'],[service]);
const upd=(k:string,v:string)=>setDetails({...details,[k]:v});return <div className="formWrap"><div className="progress"><div style={{width:`${step/total*100}%`}}/></div>{step===1&&<><div className="tag">01 — Service</div><h2>{ar?'ماذا تريد أن نبني لك؟':'What would you like us to build?'}</h2><div className="optionGrid">{services.map(([id,ic,a,e])=><button key={id} onClick={()=>setService(id)} className={`option ${service===id?'active':''}`}><div style={{fontSize:28}}>{ic}</div><h3>{ar?a:e}</h3></button>)}</div><div className="actions" style={{marginTop:24}}><button className="btn primary" disabled={!service} onClick={()=>setStep(2)}>{ar?'التالي':'Next'}</button></div></>}
{step===2&&<><div className="tag">02 — Type</div><h2>{ar?'حدد نوع المشروع':'Choose the project type'}</h2><div className="optionGrid">{types.map(x=><button key={x} onClick={()=>upd('type',x)} className={`option ${details.type===x?'active':''}`}>{x}</button>)}</div><div className="actions" style={{marginTop:24}}><button className="btn" onClick={()=>setStep(1)}>{ar?'رجوع':'Back'}</button><button className="btn primary" disabled={!details.type} onClick={()=>setStep(3)}>{ar?'التالي':'Next'}</button></div></>}
{step===3&&<><div className="tag">03 — Scope</div><h2>{ar?'ساعدنا نفهم النطاق':'Help us understand the scope'}</h2><label>{ar?'الميزانية المتوقعة':'Estimated budget'}<select className="field" value={details.budget||''} onChange={e=>upd('budget',e.target.value)}><option value="">—</option><option>2,500–5,000 QAR</option><option>5,000–10,000 QAR</option><option>10,000–20,000 QAR</option><option>20,000–50,000 QAR</option><option>50,000+ QAR</option></select></label><br/><label>{ar?'موعد الإطلاق':'Target launch'}<select className="field" value={details.timeline||''} onChange={e=>upd('timeline',e.target.value)}><option value="">—</option><option>Within 2 weeks</option><option>Within 30 days</option><option>1–2 months</option><option>2–3 months</option><option>Flexible</option></select></label><div className="actions" style={{marginTop:24}}><button className="btn" onClick={()=>setStep(2)}>{ar?'رجوع':'Back'}</button><button className="btn primary" disabled={!details.budget||!details.timeline} onClick={()=>setStep(4)}>{ar?'التالي':'Next'}</button></div></>}
{step===4&&<><div className="tag">04 — Contact</div><h2>{ar?'جاهز. أرسل بياناتك':'Your brief is ready.'}</h2><input className="field" placeholder={ar?'الاسم':'Name'}/><input className="field" placeholder={ar?'الشركة':'Company'}/><input className="field" placeholder={ar?'البريد الإلكتروني':'Email'}/><input className="field" placeholder={ar?'رقم الجوال / واتساب':'Phone / WhatsApp'}/><textarea className="field" rows={5} placeholder={ar?'اشرح لنا المشكلة أو النتيجة التي تريد الوصول إليها':'Tell us the problem or outcome you want to achieve'}/><div className="card" style={{marginTop:18,minHeight:0}}><div className="mini">{ar?'ملخص الطلب':'Request summary'}</div><p><b>{service}</b> → {details.type}<br/>{details.budget} • {details.timeline}</p></div><div className="actions" style={{marginTop:24}}><button className="btn" onClick={()=>setStep(3)}>{ar?'رجوع':'Back'}</button><button className="btn primary" onClick={()=>alert(ar?'تم تجهيز الطلب للربط مع قاعدة البيانات.':'Request is ready to connect to the database.')}>{ar?'طلب عرض سعر':'Request Proposal'}</button></div></>}
</div>}
