import Image from 'next/image';

export default async function Page({params}:{params:Promise<{locale:string}>}){const {locale}=await params;const ar=locale!=='en';return <main>
<section className="pageHero"><div className="container"><div className="eyebrow">{ar?'الأعمال':'Work'}</div><h1>{ar?'مشاريع مبنية حول نتيجة، وليس مجرد شكل.':'Projects built around outcomes, not just visuals.'}</h1><p>{ar?'نعرض هنا صورًا حقيقية من المشاريع، مع الهدف التجاري أو التشغيلي الذي كان وراء كل تجربة.':'Here we show real project imagery together with the business or operational goal behind each experience.'}</p></div></section>
<section className="section alt"><div className="container"><div className="projectGrid">
<article className="project projectWithImage"><div className="eyebrow">E-Commerce + Operations</div><h3>Doha Roastery</h3><p>{ar?'تجربة تجارة إلكترونية وربط بالطلبات والعمليات الرقمية.':'Commerce, ordering and digital operations.'}</p><div className="projectImage projectImagePage"><Image src="/projects/doha-roastery.svg" alt="Doha Roastery project cover" fill sizes="(max-width: 900px) 100vw, 50vw"/></div></article>
<article className="project projectWithImage"><div className="eyebrow">Travel</div><h3>Plaza Sky</h3><p>{ar?'واجهة سفر وحجز حديثة وسهلة الاستخدام.':'A modern, easy-to-use travel and booking experience.'}</p><div className="projectImage projectImagePage"><Image src="https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=85&w=1200" alt="Plaza Sky travel experience" fill sizes="(max-width: 900px) 100vw, 50vw"/></div></article>
<article className="project"><div className="eyebrow">Business Systems</div><h3>ERP / CRM</h3><p>{ar?'أنظمة داخلية مصممة حول احتياج الفريق والتشغيل.':'Internal systems shaped around operations and team needs.'}</p><div className="projectVisual simple"><div className="projectFrame"/></div></article>
<article className="project"><div className="eyebrow">Digital Products</div><h3>{ar?'حلول مخصصة':'Custom Solutions'}</h3><p>{ar?'منتجات رقمية مخصصة حسب احتياج القطاع وطريقة العمل.':'Custom digital products based on the industry and operating model.'}</p><div className="projectVisual simple light"/></article>
</div></div></section>
</main>}